{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gg-base.serviceAccountName" . }}
  labels:
{{ include "gg-base.labels" . | nindent 4 }}
{{- end -}}
